### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by sam01101** [sam01101/livetube#7]
- [ ] Split `Studio` to `Studio` and `Playlist`
- [ ] Add more functionallity to `Membership`
	- [ ] Stickers
	- [ ] Level
- [ ] Add livestream chat fetch support
- [ ] Remove `display_chinese` in `Video`

Welcome to give ideas
